version: '3.9'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}

    ports:
      - "1433:1433"

    networks:
      - product-network
       
    volumes:
    - sql-data:/var/opt/mssql


  api:
    build:
      context: ./
      dockerfile: Dockerfile

    container_name: myapi

    depends_on:
      - sqlserver       

    ports:
      - "5000:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;
        Database=ProductDb;
        User Id=sa;
        Password=${SA_PASSWORD};
        TrustServerCertificate=True;

    networks:
      - product-network


# define the custom network
networks:
  product-network:
    driver: bridge

volumes:
  sql-data:
  